apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-app-ingress
  namespace: test-app
  annotations:
    alb.ingress.kubernetes.io/load-balancer-arn: arn:aws:elasticloadbalancing:us-east-1:381492266480:loadbalancer/net/ae5fb9c0fdd7c43a5b3bd76a8ff176ac/6422f4041430e4fd
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
spec:
  rules:
    - host: digidense.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
