apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-app-ingress
  namespace: test-app
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - host: www.devopswizard.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
